service: test-intnl

# plugins:
#   - serverless-s3-sync

custom:
  stages:
    - dev
    - qa
    - prod

provider:
  name: aws
  region: us-east-1
  # region: us-west-2
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  deploymentBucket:
    name: ${opt:s3BucketName, 'dev-test-intnl'}
  environment:
    USERNAME: /${self:provider.stage}/name
    NAME: /${self:provider.stage}/company
    region: ${self:provider.region}
    STAGE: ${self:provider.stage}
